name: "CodeCoverage"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Test With Coverage
        run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /examples)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Run Vet & Lint
        run: |
          go vet $(go list ./... | grep -v /examples)
          golint -set_exit_status=1 $(go list ./... | grep -v /examples)